### ISSUE TITLE
Display (hello world) example not working

### ISSUE THREAD

**Issue by J0hn-Lawrence** [stm32-rs/stm32f429i-disc#8]
Hello all,

I am trying to use the led example for the f429i disco board with it´s integrated display.

The steps I did so far:
1) Installed the arm toolchain with rustup
2) Build the hello world display example with: "$ cargo build --release --example i2c_hal_ssd1306helloworld"
3) Flash it to the board by dragging the build result to the board in the file browser: 
from: /home/myusername/repositories/stm32f429i-disc/target/thumbv7em-none-eabihf/release/examples
to: /run/media/myusername/DIS_F429ZI
4) The board sits "idle" and does nothing besides the screen backlight beeing on. No text displayed. 

I got the led and the button example to work flawlessly by using the same method, so I am kind of confused as to what might be wrong here. Hoping to get some input on what I could try. 

My system: Fedora 37, all packages updated

Thank you!

**Comment by John-K** [comment]
Try without `--release`. For some reason `ssd1306` is only listed as a dev dependency

**Comment by burrbull** [comment]
> Try without `--release`. For some reason `ssd1306` is only listed as a dev dependency

`dev-dependencies` are for using in tests and examples. This is not about dev/release builds.

**Comment by J0hn-Lawrence** [comment]
Thanks for the suggestion! As I do not have the hardware anymore I think this issue should be closed, as I can not reproduce / test anymore.
